import React, { useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useAppSelector } from '@/components/redux/store';
import Modal from '@/components/Modal';
import Signup from '@/components/SignupComponent';
import Main from './Main';

const inter = Inter({ subsets: ['latin'] });


export default function Home() {
  const { user } = useAppSelector(state => state.user);

  console.log(user)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        {
          !!user.username
            ? <Main />
            :
            <Modal isOpen={true} onClose={(e) => console.log(e)}>
              <Signup />
            </Modal>
        }
      </main>
    </>
  )
}
